global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'docker-for-mac'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
  - job_name: 'web'
    static_configs:
      - targets: ['web:9117']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
