global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'docker-for-mac'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
  - job_name: 'apache'
    static_configs:
      - targets: ['apache-exporter:9117']
  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9253']
  - job_name: 'memcached'
    static_configs:
      - targets: ['memcached-exporter:9150']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
