version: '3'

x-template: &flyway-cmd
  build: ./flyway
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf
  depends_on:
    mysql:
      condition: service_healthy
  profiles:
    - flyway
  networks:
    - net

x-schemaspy-cmd: &schemaspy-cmd
  build: ./schemaspy
  volumes:
    - ./schemaspy/local.properties:/schemaspy.properties
    - ./schemaspy/output:/output
  environment:
    SCHEMASPY_OUTPUT: /output
  depends_on:
    mysql:
      condition: service_healthy
  profiles:
    - schemaspy
  networks:
    - net

x-mysql: &mysql-base
  build: ./mysql
  platform: linux/x86_64
  volumes:
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/init_scripts:/docker-entrypoint-initdb.d
  networks:
    - net

services:

  web:
    build: ./web
    container_name: web
    platform: linux/x86_64
    privileged: true
    volumes:
      - ./web/healthcheck.txt:/var/www/html/healthcheck.txt
      - ./web/.htaccess:/var/www/html/.htaccess
      - ./web/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./web/server-status.conf:/etc/httpd/conf.d/server-status.conf
      - ./web/xhprof-html.conf:/etc/httpd/conf.modules.d/xhprof-html.conf
      - ./web/php-fpm.conf:/etc/httpd/conf.modules.d/php-fpm.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - net
    healthcheck:
      test: "curl -f http://localhost/healthcheck.txt || exit 1"
      start_period: 30s
      retries: 3
      timeout: 10s
      interval: 10s

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    depends_on:
      - php-fpm
    networks:
      - net

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./php-fpm/CodeIgniter-3.1.13/application:/var/www/application
      - ./php-fpm/CodeIgniter-3.1.13/system:/var/www/system
      - ./php-fpm/index.php:/var/www/html/index.php
      - ./php-fpm/info.php:/var/www/html/info.php
      - ./php-fpm/xdebug.ini:/etc/opt/remi/php74/php.d/xdebug.ini
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - net

  memcached:
    build: ./memcached
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - net

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - net

  mysql:
    <<: *mysql-base
    container_name: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: "30s" # 起動までの時間
      retries: 3          # 許容する失敗回数
      timeout: "5s"       # 許容するレスポンスタイム
      interval: "30s"     # ヘルスチェックの間隔

  mysql-test:
    <<: *mysql-base
    container_name: mysql-test
    ports:
      - 127.0.0.1:3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}_test
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: "10s" # 起動までの時間
      retries: 3          # 許容する失敗回数
      timeout: "5s"       # 許容するレスポンスタイム
      interval: "60s"     # ヘルスチェックの間隔

  flyway-cmd:
    container_name: flyway-cmd
    <<: *flyway-cmd

  flyway-baseline:
    container_name: flyway-baseline
    <<: *flyway-cmd
    command: baseline

  flyway-migrate:
    container_name: flyway-migrate
    <<: *flyway-cmd
    command: migrate

  flyway-info:
    container_name: flyway-info
    <<: *flyway-cmd
    command: info

  schemaspy-cmd:
    container_name: schemaspy-cmd
    <<: *schemaspy-cmd

  xhgui:
    build: ./xhgui
    container_name: xhgui
    restart: always
    volumes:
      - ./xhgui/config:/var/www/xhgui/config
      - ./xhgui/nginx.conf:/etc/nginx/http.d/default.conf:ro
    environment:
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "8142:80"
    networks:
      - net

  mongo:
    build: ./mongo
    container_name: mongo
    platform: linux/x86_64
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./mongo/init.d:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - net

  prometheus:
    build: ./prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - net

  grafana:
    build: ./grafana
    container_name: grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    networks:
      - net

  apache-exporter:
    build: ./apache-exporter
    container_name: apache-exporter
    privileged: true
    ports:
      - mode: ingress
        target: 9117
        published: "9117"
        protocol: tcp
    restart: unless-stopped
    entrypoint: /bin/apache_exporter --scrape_uri="http://web/server-status?auto"
    networks:
      - net
    depends_on:
      web:
        condition: service_healthy

  nginx-exporter:
    build: ./nginx-exporter
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    restart: unless-stopped
    entrypoint: nginx-prometheus-exporter -nginx.scrape-uri=http://nginx/nginx_status
    networks:
      - net
    depends_on:
      - nginx

  php-fpm-exporter:
    build: ./php-fpm-exporter
    container_name: php-fpm-exporter
    restart: unless-stopped
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://php-fpm:9000/status"
      PHP_FPM_LOG_LEVEL: "debug"
    ports:
      - 9253:9253
    networks:
      - net

  redis-exporter:
    build: ./redis-exporter
    container_name: redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - 9121:9121
    networks:
      - net

  memcached-exporter:
    build: ./memcached-exporter
    container_name: memcached-exporter
    restart: unless-stopped
    command: --memcached.address memcached:11211
    ports:
      - 9150:9150
    networks:
      - net

  mysqld-exporter:
    build: ./mysqld-exporter
    container_name: mysqld-exporter
    command:
      - --collect.info_schema.tablestats
    environment:
      DATA_SOURCE_NAME: ${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}@${MYSQL_EXPORTER_TARGET}
    ports:
      - 9104:9104
    networks:
      - net
    depends_on:
      mysql:
        condition: service_healthy

  influxdb:
    build: ./influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
    ports:
      - "8086:8086"
    networks:
      - net

  k6-cmd:
    build: ./k6
    container_name: k6
    platform: linux/x86_64
    volumes:
      - ./k6/scripts:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    ports:
      - "6565:6565"
    networks:
      - net
    profiles:
      - k6

networks:
  net:
