version: '3'

services:
  app:
    build: .
    container_name: amzn-linux-2-app
    platform: linux/x86_64
    privileged: true
    volumes:
      - ./CodeIgniter-3.1.13/application:/var/www/application
      - ./CodeIgniter-3.1.13/system:/var/www/system
      - ./index.php:/var/www/html/index.php
      - ./info.php:/var/www/html/info.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
      - ./xhprof-html.conf:/etc/httpd/conf.modules.d/xhprof-html.conf
      - ./xdebug.ini:/etc/opt/remi/php74/php.d/xdebug.ini
    ports:
      - 8080:80