version: '3'

services:
  app:
    build: .
    container_name: amzn-linux-2-app
    platform: linux/x86_64
    privileged: true
    volumes:
      - ./CodeIgniter-3.1.13/application:/var/www/application
      - ./CodeIgniter-3.1.13/system:/var/www/system
      - ./index.php:/var/www/html/index.php
      - ./info.php:/var/www/html/info.php
    ports:
      - 8080:80
