version: '3'

x-template: &flyway-cmd
  build: ./flyway
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf
  depends_on:
    mysql:
      condition: service_healthy
  profiles:
    - flyway
  networks:
    - net

x-schemaspy-cmd: &schemaspy-cmd
  build: ./schemaspy
  volumes:
    - ./schemaspy/local.properties:/schemaspy.properties
    - ./schemaspy/output:/output
  environment:
    SCHEMASPY_OUTPUT: /output
  depends_on:
    mysql:
      condition: service_healthy
  profiles:
    - schemaspy
  networks:
    - net

x-mysql: &mysql-base
  build: ./mysql
  platform: linux/x86_64
  volumes:
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  networks:
    - net

services:

  web:
    build: ./web
    container_name: web
    platform: linux/x86_64
    privileged: true
    volumes:
      - ./web/CodeIgniter-3.1.13/application:/var/www/application
      - ./web/CodeIgniter-3.1.13/system:/var/www/system
      - ./web/index.php:/var/www/html/index.php
      - ./web/info.php:/var/www/html/info.php
      - ./web/.htaccess:/var/www/html/.htaccess
      - ./web/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./web/xhprof-html.conf:/etc/httpd/conf.modules.d/xhprof-html.conf
      - ./web/xdebug.ini:/etc/opt/remi/php74/php.d/xdebug.ini
    ports:
      - 8080:80
    networks:
      - net

  mysql:
    <<: *mysql-base
    container_name: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: "10s" # 起動までの時間
      retries: 3          # 許容する失敗回数
      timeout: "5s"       # 許容するレスポンスタイム
      interval: "60s"     # ヘルスチェックの間隔

  mysql-test:
    <<: *mysql-base
    container_name: mysql-test
    ports:
      - 127.0.0.1:3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}_test
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: "10s" # 起動までの時間
      retries: 3          # 許容する失敗回数
      timeout: "5s"       # 許容するレスポンスタイム
      interval: "60s"     # ヘルスチェックの間隔

  flyway-cmd:
    <<: *flyway-cmd

  flyway-baseline:
    <<: *flyway-cmd
    command: baseline

  flyway-migrate:
    <<: *flyway-cmd
    command: migrate

  flyway-info:
    <<: *flyway-cmd
    command: info

  schemaspy-cmd:
    <<: *schemaspy-cmd

  prometheus:
    build: ./prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

networks:
  net:
